#!/usr/bin/env php
<?php
if (! getenv('APP_PATH')) {
    throw new \Exception('Must set environment APP_PATH to run apicon.');
}
/*
 * @codingStandardsIgnoreFile
 */
/** @var \B2k\Apitude\Application $app */
$app = require_once getenv('APP_PATH').'/bootstrap.php';
$app->runConsole();
