#!/usr/bin/env php
<?php
/*
 * @codingStandardsIgnoreFile
 */
/** @var \Apitude\Core\Application $app */
if (!defined('APP_PATH')) {
    define('APP_PATH', realpath(__DIR__.'/../../..'));
}
$app = require_once APP_PATH.'/bootstrap.php';
$app->runConsole();
